document.addEventListener("DOMContentLoaded", async () => {
    "use strict";
    const API="https://project-hub-backend-1.onrender.com", LOGIN="../auth/login.html", KEY="projectHubPlaces";
    const $=id=>document.getElementById(id), token=()=>localStorage.getItem("projectHubAuthToken");
    const list=$('placesList'), meta=$('placesMeta'), search=$('placesSearch'), modal=$('placeModal'), form=$('placeForm');
    let places=[], filter="all", editingId=null;
    function headers(){return {Authorization:"Bearer "+token(),"Content-Type":"application/json"};}
    function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML;}
    function saveLocal(){localStorage.setItem(KEY,JSON.stringify(places));}
    function local(){try{const x=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
    async function request(path,opts={}){const r=await fetch(API+path,{credentials:"include",...opts,headers:{...headers(),...(opts.headers||{})}}); if(r.status===401) throw new Error("AUTH"); const data=await r.json().catch(()=>({})); if(!r.ok||data.success===false) throw new Error(data.message||"Hiba történt."); return data;}
    function categoryClass(p){return String(p.category||"").toLowerCase().includes("étter")?"food":String(p.category||"").toLowerCase().includes("város")?"city":"other"}
    function visible(){const q=search.value.trim().toLocaleLowerCase("hu-HU");return places.filter(p=>(filter==="all"||(filter==="favorite"&&p.favorite)||(filter!="favorite"&&categoryClass(p)===filter))&&(!q||[p.name,p.category,p.address,p.notes].join(" ").toLocaleLowerCase("hu-HU").includes(q))).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||new Date(b.updated_at||0)-new Date(a.updated_at||0));}
    function render(){const v=visible();meta.textContent=`${v.length} megjelenített hely · ${places.length} összesen`;if(!v.length){list.innerHTML='<div class="places-state"><span><i class="fi fi-br-marker ui-icon" aria-hidden="true"></i></span><strong>Nincs találat</strong><p>Adj hozzá egy helyet, vagy módosítsd a szűrést.</p></div>';return;}list.innerHTML="";v.forEach(p=>{const card=document.createElement("article");card.className="place-item";card.innerHTML=`<div class="place-icon">${p.favorite?'<i class="fi fi-br-star ui-icon" aria-hidden="true"></i>':'<i class="fi fi-br-marker ui-icon" aria-hidden="true"></i>'}</div><div class="place-copy"><div class="place-heading"><h3>${esc(p.name)}</h3><span>${esc(p.category||'Egyéb')}</span></div>${p.address?`<p class="place-address">${esc(p.address)}</p>`:''}${p.notes?`<p class="place-notes">${esc(p.notes)}</p>`:''}</div><div class="place-item-actions"><button class="icon-action fav" type="button" title="Kedvenc"><i class="fi fi-br-star ui-icon" aria-hidden="true"></i></button><button class="icon-action edit" type="button" title="Szerkesztés"><i class="fi fi-br-pencil ui-icon" aria-hidden="true"></i></button><button class="icon-action delete" type="button" title="Törlés"><i class="fi fi-br-cross-small ui-icon" aria-hidden="true"></i></button></div>`;
        card.querySelector('.fav').onclick=()=>mutate(p.id,{favorite:!p.favorite}); card.querySelector('.edit').onclick=()=>openModal(p); card.querySelector('.delete').onclick=()=>remove(p); list.appendChild(card);});}
    async function load(){try{const d=await request('/api/places');places=Array.isArray(d.places)?d.places:[];saveLocal();render();}catch(e){if(e.message==='AUTH'){localStorage.removeItem('projectHubAuthToken');sessionStorage.setItem('projectHubAuthMessage','A munkameneted lejárt. Jelentkezz be újra.');location.href=LOGIN;return;}places=local();render();meta.textContent+= ' · offline mód';}}
    async function mutate(id,patch){const old=places.find(p=>String(p.id)===String(id));if(!old)return;Object.assign(old,patch);render();try{const d=await request('/api/places/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(patch)});Object.assign(old,d.place);saveLocal();render();}catch(e){saveLocal();}}
    async function remove(p){if(!confirm(`„${p.name}” törlése?`))return;places=places.filter(x=>String(x.id)!==String(p.id));render();try{await request('/api/places/'+encodeURIComponent(p.id),{method:'DELETE'});saveLocal();}catch{saveLocal();}}
    function openModal(p=null){editingId=p?.id??null;form.reset();$('placeModalTitle').textContent=p?'Hely szerkesztése':'Hely hozzáadása';$('placeId').value=p?.id||'';$('placeName').value=p?.name||'';$('placeCategory').value=p?.category||'Egyéb';$('placeAddress').value=p?.address||'';$('placeNotes').value=p?.notes||'';$('placeFavorite').checked=!!p?.favorite;modal.hidden=false;document.body.classList.add('modal-open');setTimeout(()=>$('placeName').focus(),30)}
    function close(){modal.hidden=true;document.body.classList.remove('modal-open')}
    form.addEventListener('submit',async e=>{e.preventDefault();const payload={name:$('placeName').value.trim(),category:$('placeCategory').value,address:$('placeAddress').value.trim(),notes:$('placeNotes').value.trim(),favorite:$('placeFavorite').checked};if(!payload.name)return;if(editingId){await mutate(editingId,payload)}else{try{const d=await request('/api/places',{method:'POST',body:JSON.stringify(payload)});places.unshift(d.place);saveLocal();}catch{places.unshift({id:'local-'+Date.now(),...payload,updated_at:new Date().toISOString()});saveLocal();}render()}close()});
    $('addPlaceButton').onclick=()=>openModal();$('closePlaceButton').onclick=close;$('cancelPlaceButton').onclick=close;document.querySelector('.place-overlay').onclick=close;search.oninput=render;
    document.querySelectorAll('.place-filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.place-filter').forEach(x=>x.classList.toggle('active',x===b));render()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close()});
    try{const r=await request('/api/auth/me');if(!r.success||!r.user)throw new Error('AUTH');document.body.classList.add('authenticated');}catch{localStorage.removeItem('projectHubAuthToken');sessionStorage.setItem('projectHubAuthMessage','A munkameneted lejárt. Jelentkezz be újra.');location.href=LOGIN;return} await load();
});
